version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network: